# Generated by Django 4.2.3 on 2023-09-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
